name = "Firsr PyScript App"
description = "An example of how to build pyscript app."
packages = ["Pillow", "distinctipy"]
[files]
"{FROM}" = "http://localhost:5500"
"{TO}" = "."

"{FROM}/src/manager.py" = "{TO}/"
"{FROM}/src/file_manager.py" = "{TO}/"
"{FROM}/src/const.py" = "{TO}/"
"{FROM}/src/fileformat_handler.py" = "{TO}/"
"{FROM}/assets/Anonymous_Pro.ttf" = "{TO}/assets/Anonymous_Pro.ttf"

# END COMMON PART
"{FROM}/data/docs/10002/epi_apollonia.pap" = "{TO}/data/docs/10002/epi_apollonia.pap"

