name = "Firsr PyScript App"
description = "An example of how to build pyscript app."
packages = ["Pillow", "distinctipy"]
[files]
"{FROM}" = ""
"{TO}" = "."

"{FROM}/src/manager.py" = "{TO}/"
"{FROM}/src/file_manager.py" = "{TO}/"
"{FROM}/src/const.py" = "{TO}/"
"{FROM}/src/fileformat_handler.py" = "{TO}/"
"{FROM}/assets/Anonymous_Pro.ttf" = "{TO}/assets/Anonymous_Pro.ttf"

# END COMMON PART
"{FROM}/data/docs/10004/TM3563_P.Tor.Choach.12.01.pap" = "{TO}/data/docs/10004/TM3563_P.Tor.Choach.12.01.pap"
